# Generated by Django 4.0.2 on 2022-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_round', models.IntegerField(default=1)),
                ('current_status', models.IntegerField(choices=[(1, 'NOT_EVALUATED'), (2, 'EVALUATED'), (3, 'ELIMINATED')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
