# Generated by Django 3.2.6 on 2022-02-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_round', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('N', 'NORMAL'), ('I', 'IMAGE')], max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
