# Generated by Django 4.0.2 on 2022-02-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaeAudition', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
