# Generated by Django 4.0.2 on 2022-02-13 07:57

import SaeAudition.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_remove_profile_id_profile_first_name_and_more'),
        ('SaeAudition', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_round', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('T', 'TEXT'), ('I', 'IMAGE'), ('M', 'MCQ')], default='T', max_length=1)),
                ('question_text', models.CharField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='images', validators=[SaeAudition.models.validate_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('profile', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='username', to='register.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='SaeAudition.question')),
            ],
        ),
    ]
