# Generated by Django 4.0.2 on 2022-02-13 18:18

import SaeAudition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaeAudition', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[SaeAudition.models.validate_image_size]),
        ),
    ]
