# Generated by Django 4.0.2 on 2022-02-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaeAudition', '0004_alter_question_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
