# Generated by Django 4.0.2 on 2022-02-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_profile_first_name_remove_profile_last_name_and_more'),
        ('SaeAudition', '0005_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('profile', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='username', to='register.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='SaeAudition.question')),
            ],
        ),
    ]
