# Generated by Django 3.2.6 on 2022-02-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_profile_first_name_profile_last_name_and_more'),
        ('SaeAudition', '0006_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='register.profile'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allanswer', to='SaeAudition.question'),
        ),
    ]
